### ISSUE TITLE
Bolso won't display any article

### ISSUE THREAD

**Issue by Mno-hime** [felipeborges/bolso#10]
I compiled bolso from git, manually created ~/.cache/bolso/, and executed it from command line. Bolso displays the list of saved articles correctly (it probably reads credentials from goa) but when I open any item, Bolso displays empty page. I don't see any error in terminal, just:

```
bolso $ ./src/bolso 
Gjs-Message: JS LOG: Running from source tree, using local files
openjdk version "1.8.0_71"
OpenJDK Runtime Environment (build 1.8.0_71-b15)
OpenJDK 64-Bit Server VM (build 25.71-b15, mixed mode)
```

After that Bolso won't even try to open another article just sticks to "My List".

**Comment by felipeborges** [comment]
I'm sure this one is fixed by the latest refactoring.  Please reopen if that's not the case for you.
